
package mang.demo.cxf.server.stub.demo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-20T18:00:23.599+08:00
 * Generated source version: 3.2.1
 * 
 */
 
public class WsDemoService_WsDemoServicePort_Server{

    protected WsDemoService_WsDemoServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new WsDemoServicePortImpl();
        String address = "http://127.0.0.1:8080/cxf-spring/services/demoService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new WsDemoService_WsDemoServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
