
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package mang.demo.cxf.server.stub.demo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-20T18:00:23.588+08:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsDemoServiceService",
                      portName = "WsDemoServicePort",
                      targetNamespace = "http://ws.spring.cxf.demo.mang/",
                      wsdlLocation = "file:/c:/Users/mang/Desktop/WsDemoServiceService.wsdl",
                      endpointInterface = "mang.demo.cxf.server.stub.demo.WsDemoService")
                      
public class WsDemoServicePortImpl implements WsDemoService {

    private static final Logger LOG = Logger.getLogger(WsDemoServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see mang.demo.cxf.server.stub.demo.WsDemoService#sayHello(java.lang.String arg0)*
     */
    public java.lang.String sayHello(java.lang.String arg0) { 
        LOG.info("Executing operation sayHello");
        System.out.println(arg0);
        try {
            java.lang.String _return = "这是自己实现的服务类"+arg0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
